name: redpred
channels:
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - rdkit
    - pip
    - pip:
        - streamlit==0.84.0
        - scikit-learn==0.22.1
        - pandas==1.0.3
        - numpy==1.18.5
        - tensorflow==2.3.2
        - keras==2.4.3
        - deepchem==2.4.0
